### ISSUE TITLE
Allow overriding repo

### ISSUE THREAD

**Issue by viceice** [uhop/install-artifact-from-github#6]
I like to change the github repo to download artifacts from a mirror.

sample: https://github.com/containerbase/node-re2-prebuild

I've prebuild re2 binaries, but how to simply override the github repo for download?

**Comment by uhop** [comment]
It looks like this specific question belongs to `node-re2`. See if https://github.com/uhop/node-re2/wiki/Precompiled-versions#private-mirrors answers your question.

**Comment by viceice** [comment]
I know that page and it's now working. But it would be much simpler to only override the org and repo part.

```console
# using node v20.10,0 on aarch64
> export RE2_MIRROR_REPO=containerbase/node-re2-prebuild
> npm install -g re2@1.20.9
# load from https://github.com/containerbase/node-re2-prebuild/releases/download/1.20.9/linux-arm64-115.br
```

🙃

**Comment by uhop** [comment]
>But it would be much simpler to only override the org and repo part.

It would be in this specific case, but it is not generic. You are the first to use GitHub to host custom artifacts. Most customers use corporate mirrors hosted internally.
